<?php
/** PLACE THIS ON WP-CONFIG.PHP OF THE PRODUCTION SITE. CHANGE THE URL AS NEEDED.
* IF THE SITE IT'S COPIED TO HAS A DIFFERENT URL, IT WILL DEFINE ENVIRONMENT AS A STAGING SITE.
* OMNISEND WILL NOT SET THE WEBSITE VALUE IN THEIR ADMIN TO BE A STAGING SITE.
*
*//
if ( isset($_SERVER['HTTP_HOST']) && $_SERVER['HTTP_HOST'] !== 'paylesskratom.com' ) {
define('WP_ENVIRONMENT_TYPE', 'staging');
}

